### ISSUE TITLE
Reduce size of nonces associated with coinbase scriptSig

### ISSUE THREAD

**Issue by ASICseer** [ASICseer/asicseer-pool#10]
**Environment**

coinbase scriptSig in found blocks.

**Feature Description**

* Determine if nonce byte size uses bytes from the maximum 100-byte limit.
* Reduce nonce size.

**Steps to Reproduce**

Mine a block and check expected result:

**Expected Result**

The `&Aring;&Ouml; �  Hh^  D  +Fh^A ������` portion of 
`&Aring;&Ouml; �  Hh^  D  +Fh^A ������ /pool.ASICseer.com calin BCHN/` should be as small as possible.

**Comment by cculianu** [comment]
A lot of the data in there seems to be custom-crafted to make the work-unit as unique as possible. Here's some of the stuff that CK encoded in there:

- block height (4 bytes)
- nonce1 (4 bytes, user configurable size here actually)
- nonce2 (8 bytes, user configurable size here)
- timestamp (seconds, nanoseconds) of when the work unit was created (8 bytes)

Plus a few other tiny things.  I believe the above is all there to prevent cheating.  If the work unit is as unique as possible, down to a nanosecond timestamp and nonces, it prevents cheaters from taking the same work unit and submitting it twice, etc.  I *think* that's why all this stuff is so carefully placed there.

I hesitate to reduce that stuff, really -- given the reason I think it's there.  I'm not sure though -- but that's what I suspect.

This is a slightly new problem domain for me so I can't be certain yet...
