### ISSUE TITLE
Consider removal of extra data from coinbase scriptsig

### ISSUE THREAD

**Issue by tfaoro** [ASICseer/asicseer-pool#16]

**Comment by cculianu** [comment]
Yeah man good call.  There's all this crap that's inserted before the first '`/`' character in the coinbase scriptsig.  For (my and your) reference, here's the stuff inserted:

- `block_height` - (4 bytes), **this is required** as per BTC/BCH consensus rules as of [BIP34](https://github.com/bitcoin/bips/blob/master/bip-0034.mediawiki).
- `flags_length` - (1 byte), this is always 0 for now.  But it takes up 1 byte. It's the length of the `flags` field that follows.
- `flags` - which is byte data that comes from `getblocktemplate`'s `["coinbaseaux"]["flags"]` response (currently always 0 bytes).
- `timestamp` - (7-10 bytes). Basically `struct timespec.tv_sec`  + `timespec.tv_nsec`, in a compact form.  This is seconds + nanoseconds (with length bytes), basically.
- `nonce_length` - (1 byte) - The total length of the two `nonce#` fields below. 
- `nonce1` - (2-8 bytes) - Some random bytes. The length of this is configurable as conf file variable `nonce1length`.  Default if unspecified: `4` bytes.
-   `nonce2` - (2-8 bytes) - Some random bytes again. The length of this is configurable as conf file variable `nonce2length`. Default if unspecified: `8` bytes if !proxy mode, `0` bytes otherwise.
- `coinbase_sig_string_len` - (1 byte) - The length of the below `coinbase_sig_string` field.
- `coinbase_sig_string` - (variable, up to remainder of 100-byte space that's left [usually about ~73 bytes)


With the exception of `block_height` above (which is required by bitcoin), potentially all of the above can be removed.  However it looks like ck went to great care to nonceify and otherwise uniquely mark each work unit generated by doing this to the coinbase.  I can't be sure yet what effects removing this data has on mining, or on forging work unit results to game the hash rate, etc.  I have to be very careful here.

This response is just to illuminate the discussion so we know what is there (and what can be potentially removed).

**Comment by cculianu** [comment]
I pushed a commit just now that removes some of this data, but still leaves some of it. Here is the data removed:

- `flags_length`, 1 byte
- `flags`, 0-4 bytes
- `coinbase_sig_string_len`,  1 byte

In addition, the `timestamp` field has been made a fixed size, 8-byte integer.  This shaves off 2 bytes of average.

On average about 4 bytes were saved. Not a huge savings.  I'm wary to delete the other fields (especially the `timestamp` and the `nonce_length`) because I'm unclear yet what they do.  I am also unclear about how the pool defends against attacks where a user can fake their hash rate by submitting multiple duplicate shares.  I suspect the `timestamp` plays into this.

**Comment by cculianu** [comment]
This has been fully addressed in v1.2.0 commit 3dddb6efce046139ef321dfda3ce39e2722f555a
